# Generated by Django 4.0.6 on 2022-07-20 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('city', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
