# Generated by Django 4.0.6 on 2022-07-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(default='https://djangogirls.org/en/matola/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
