# Generated by Django 2.0.9 on 2018-12-31 08:40

from django.db import migrations, models
import django.utils.timezone
from django.template.defaultfilters import slugify


def create_post_slug(apps, schema_editor):
    # We can't import the Category model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Post = apps.get_model("dgMatola", "Post")
    for row in Post.objects.all():
        row.slug = slugify(Post.name)
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181105_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titulo'),
        ),
    ]
