# Generated by Django 2.0.9 on 2019-11-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191109_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/lowerleft.png', upload_to='media/'),
        ),
    ]
